import type { Project } from "@/types/database";
import { getKnowledgeFile } from "@/lib/ai/systemPrompt";
import { formatDiscoveryBlock, formatPriorGenerationsBlock, type PriorGeneration } from "./shared";

export const VSL_CREDIT_COST = 5;
export const VSL_MAX_OUTPUT_TOKENS = 5000;

export function buildVslScriptPrompt(project: Project, priorGenerations: PriorGeneration[] = []): string {
  const structure = getKnowledgeFile("05-vsl-25-part.md");

  return `Write a full VSL (Video Sales Letter) script using the 25-part structure below for the project.

${formatDiscoveryBlock(project)}
${formatPriorGenerationsBlock(priorGenerations)}

25-PART STRUCTURE TO FOLLOW:
${structure}

Write full spoken-word script copy for each of the 25 beats, not just bullet notes — this should be close to word-for-word what the presenter says on camera or in voiceover. Keep beats tight (2-5 sentences each) so the full script stays watchable. Ground every proof/results claim in the project's "Proof" field; where no proof was supplied, write "[NEEDS PROOF: <what kind>]" instead of inventing a number or testimonial.

FORMAT — exactly this, so the label and the spoken copy are never mixed on the same line:
**N. Stage Name**
[the spoken script for this beat, 2-5 sentences]

(blank line, then the next beat the same way). The label line exists ONLY to help whoever's reading this document find their way around it — it is invisible structure, not something anyone ever hears. This means the spoken copy itself must NEVER reference, name, or announce its own beat — never write anything like "here's the big promise," "now, for the pattern interrupt," "this is the credibility bridge," or "now here's where I interrupt the pattern." No real presenter narrates their own script structure out loud. Deliver the actual content directly — the promise itself, the actual interrupt, the actual credibility — exactly as a real presenter would say it on camera, as if the beat labels didn't exist at all.

Stage 5 (Credibility Bridge) and Stage 6 (Opening Story) specifically should be built from the Presenter Bio fields, not invented: Stage 5 from years in the industry / credentials / mission; Stage 6 as a full Epiphany Bridge™ story (Playbook 10) built from whichever real fields were supplied — Backstory from the origin story, The Wall from the setback story, The Mentor from the "what or who helped you break through" field, The Epiphany from the exact "moment everything changed" field (this IS the belief being planted — state it as a discovery, not a lesson), The Conflict from the "what still went wrong after you committed" field (never flatten it into a throwaway line), The Achievement from the signature win, and The Return as the explicit bridge into Stage 7 onward: "that's exactly why I'm here today." Don't invent a fake epiphany if that field is blank but the setback story is supplied — write the turning point only as concretely as the setback story actually supports, and flag [NEEDS: the specific epiphany/insight] rather than fabricating one. Same rule for a blank Mentor field (frame it plainly as "I figured it out on my own") and a blank Conflict field (keep it light and flag [NEEDS: what went wrong after committing to the new way]). If every Presenter Bio story field is blank, flag Stage 6 as a gap needing real input rather than fabricating a story.

Stage 14 (Belief Shifting) must explicitly name the Big Domino™ (Playbook 10) — the ONE belief that, if adopted, makes every other objection in this script collapse on its own — and every other stage's belief work should visibly serve knocking down that same one belief, not several different ones.

Stage 14 itself must then use The Three Secrets™ (Playbook 10) to actually deliver that Big Domino, not treat it as a single belief dropped in one breath: break it into exactly three specific false beliefs this audience holds — one Vehicle belief (doubt about the mechanism/method itself — "does this actually work?"), one Internal belief (doubt about themselves — "can I actually do this?"), and one External belief (doubt about their circumstances — "will my situation let this work?"). Write Stage 14 as three short, labeled sub-beats (14a/14b/14c), each stating that specific false belief in this audience's own likely words (pull from discovery's objections/awareness data where available) followed by the real moment or evidence that broke it — a condensed Epiphany Bridge moment, not the full 9-beat treatment Stage 6 already got, so each sub-beat stays a tight 2-4 sentences, not a second origin story. Ground each in the project's discovery/Presenter Bio facts; if nothing supports a real moment for one of the three, write "[NEEDS: a real story/example for the Vehicle/Internal/External false belief]" for that one specifically rather than inventing it.

Stages 18-20 (Offer Construction / Value Stack / Bonuses) are one continuous batched, CUMULATIVE reveal, not three separate ideas to cover once each — never a single beat that lists the core offer, every stack item/bonus, and the total together, and NOT one sub-beat per individual item either (too many sub-beats when there are several). Use the VALUE STACK discovery data above (core offer value, each stack item/bonus and its value, the computed total, and how the price compares to it) when it's present: sub-beat 18a is the core offer alone, with its own value. Count how many stack items + bonuses exist, group them into batches of roughly 2-3 each, and give each batch its own sub-beat (18b, 18c, 18d...) — how many depends on the real count (3 items → one more sub-beat; 9 items → three more). Each of those sub-beats restates the FULL cumulative stack so far (the core offer + every item from every earlier batch + this batch's new items, each with its own value) rather than only naming what's new — the audience should hear the stack visibly growing each time, not a series of disconnected one-off mentions. A stack item (part of the core offer) and a bonus (a separate extra) are worded differently when introduced, even inside the same sub-beat. After the last batch's sub-beat, add one final sub-beat totaling it all up (the real TOTAL STACK VALUE number when the discovery data computed one — never invent a number it didn't). The price itself belongs in Stage 21 (Guarantee) or wherever this structure naturally reveals it next, and must come AFTER that total, framed explicitly against it using the ACTUAL PRICE vs. TOTAL VALUE line when present. If the discovery data has no Value Stack numbers at all, fall back to the free-text "Bonuses" field, still built as a cumulative batched recap rather than all at once, just without exact running totals to cite.

Stages 22-23 (Scarcity / Urgency) must reveal the FAST ACTION BONUS discovery data when present, right after the price and never before it or folded into Stages 18-20's own stack/total — its real item, value, and qualifying condition ("and if you're one of the [condition], I'll also include [item], worth [value]"), framed as the reason to act in this exact moment. If that discovery data is empty, these stages can still use authentic scarcity/urgency from the project's own Scarcity/urgency field instead, but must never invent a fake fast-action bonus to fill the gap.`;
}
