import type { Project } from "@/types/database";
import { formatDiscoveryBlock, formatPriorGenerationsBlock, type PriorGeneration } from "./shared";

export const WEBINAR_CREDIT_COST = 3;
export const WEBINAR_MAX_OUTPUT_TOKENS = 4000;

export function buildWebinarOutlinePrompt(project: Project, priorGenerations: PriorGeneration[] = []): string {
  return `Build a full Webinar Outline using the Pitch Perfect Webinar Operating System™ (PPWOS™) for the project below — following the classic Perfect Webinar Script's full structure (Playbooks 3 and 10), not a shortened version of it.

${formatDiscoveryBlock(project)}
${formatPriorGenerationsBlock(priorGenerations)}

Before the phases, answer this STRATEGIC SETUP (the planning questions the rest of the outline is built from — answer each in 1-2 lines):
- **The New Opportunity**: frame this offer as a new, never-tried-before mechanism/vehicle (not a better version of something the audience already tried and judged) — a New Opportunity bypasses "I already tried that," a Vehicle Improvement doesn't (Playbook 10).
- **The Big Domino™**: the ONE belief that, if adopted, makes every other objection (time, money, "will this work for someone like me," past failures) collapse on its own (Playbook 10).
- **The Special Offer**: what makes buying DURING/right after this specific webinar meaningfully better than buying later — a fast-action bonus, a founding price, something exclusive to right now. This decision drives Phase 6's bonus stack below.

Produce the outline in this structure:
1. **Phase 1 — Capture Attention**: Welcome beat, Big Promise (the outcome, not the topic — reflecting the New Opportunity framing above), agenda, opening engagement trigger (poll/chat question), then a short **Presenter Credibility Bridge** beat — who's presenting and why they're qualified to, built from the Presenter Bio fields (years in the industry, credentials, mission). Keep it tight (3-5 lines): earn the right to teach, don't deliver a full bio speech.
2. **Phase 2 — Build Relevance**: Audience identification bullets, opportunity framing, one shared-experience story beat built as a full Epiphany Bridge™ story (Playbook 10) from the real Presenter Bio fields supplied — this is the presenter's own origin story: Backstory (origin story) → Desire → Wall (setback story) → Mentor (the "what or who helped you break through" field) → Epiphany (the exact "moment everything changed" field — the belief being planted, stated as a discovery) → Plan → Conflict (the "what still went wrong after you committed" field — the darkest point, never a throwaway line) → Achievement (signature win) → Return ("that's exactly why I'm here today"). A real "I've been where you are" moment lands harder than an invented one — if the epiphany field specifically is blank, don't invent a fake realization; write the turning point only as concretely as the setback story supports. Close Phase 2 with an interactive reflection question.
3. **Phase 3 — Create New Beliefs (The Three Secrets™)**: Open by restating the Big Domino™ from Strategic Setup above. Then break it into exactly THREE specific false beliefs this audience holds about adopting it — one **Vehicle** belief (doubt about the mechanism/method itself — "does this actually work?"), one **Internal** belief (doubt about themselves — "can I actually do this?"), and one **External** belief (doubt about their circumstances — "will my situation let this work?"). State each false belief concretely in this audience's own likely words (pull from discovery's objections/awareness data where available), not a generic stand-in. For EACH of the three, write a dedicated Epiphany Bridge™ story (Playbook 10's 9 beats — Backstory → Desire → Wall → Mentor → Epiphany → Plan → Conflict → Achievement → Return) that breaks specifically that one belief — three separate stories, never one story stretched to cover more than one secret. If discovery/presenter bio doesn't support a real story for one of the three, flag it plainly (\`[NEEDS: a real story for the [Vehicle/Internal/External] false belief]\`) rather than inventing one. After each secret's story, add a "false belief removal" line ("Many people naturally assume... but...") and 1-2 micro-commitment check-in lines. Name a framework if relevant. Remember throughout: the presenter is the Guide here, not the Hero (Playbook 10) — from this phase forward, keep the focus on the AUDIENCE's own journey toward each belief shift, not back on the presenter.
4. **Phase 4 — Build Certainty**: List the proof elements to use (case study, testimonial, demonstration) — pull from the project's "Proof" field and the Presenter Bio's "Greatest client transformation" story if one was supplied; if neither exists, flag it as a gap to fill rather than inventing one.
5. **Phase 5 — Present the Solution**: One paragraph introducing the offer as the natural next step, plus a future-pacing beat (30/90/365 days).
6. **Phase 6 — Maximize Value**: Core offer summary, bonus stack (map each bonus to the objection it removes, and make sure the Special Offer from Strategic Setup above is the standout bonus here), investment framing, guarantee.
7. **Phase 7 — Drive Commitment**: Scarcity/urgency tied to the Special Offer being time-limited (only if authentic — otherwise note "no authentic urgency mechanism supplied"), risk removal, and the single specific CTA repeated 2-3 times through this section.

Keep each phase to a one-screen block: a one-line strategic objective followed by bullet beats — not full prose script, except the Three Secrets' stories in Phase 3, which each need enough beats to actually land (not compressed to one line each). This is a skeleton a presenter builds slides and talk track from, not a word-for-word script.`;
}
